[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/dsa"
  to = "/dsa.html"
  status = 200

[[redirects]]
  from = "/leetcode"
  to = "/leetcode.html"
  status = 200

[[redirects]]
  from = "/github"
  to = "/github.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
